#!/bin/bash
bldred=${txtbld}$(tput setaf 1)
txtrst=$(tput sgr0)

rm output/*.png 2> /dev/null

while read test_def; do
  name=`echo $test_def | cut -f1 -d,`
  output_file=`echo $test_def | cut -f3 -d,`
  test=`echo $test_def | cut -f4 -d,`
  global_result=0

  echo -n "  * running test ${name} ... "
  eval ${test} "\--output_filename" "${output_file}"
  if test $? -ne 0
  then
    echo "${bldred} FAILED${txtrst}"
    global_result=1
  else
    echo " passed"
  fi
 
done < tests.txt

echo
if test ${global_result} -eq 0
then
  echo "  ** All tests passed"
else
  echo "  ** Some tests FAILED"
fi

exit ${global_result}
