#!/bin/bash
rm output/acme_registrations*.png output/acme_revenue*.png

../plot_timeseries --verbose --width=1200 --height=700 --x_spacing=week --csv_filename=test_data/acme_registrations.csv --output_filename=output/acme_registrations.png --show_gridlines --title="Acme Registrations: %s to %s" --y_title="Number Registrations" --remove_outliers

../plot_timeseries --verbose --width=500 --height=400 --x_spacing=month --csv_filename=test_data/acme_registrations.csv --output_filename=output/acme_registrations_thumb.png --point_color=gray80 --sunday_point_color=gray80 --remove_outliers --smoothness=0.8

../plot_timeseries --verbose --width=1200 --height=700 --x_spacing=week --csv_filename=test_data/acme_revenue.csv --output_filename=output/acme_revenue.png --show_gridlines --title="Acme Revenue: %s to %s" --remove_outliers

../plot_timeseries --verbose --width=500 --height=400 --x_spacing="2 months" --csv_filename=test_data/acme_revenue.csv --output_filename=output/acme_revenue_thumb.png --point_color=gray80 --sunday_point_color=gray80 --remove_outliers --smoothness=0.8

open output/acme_revenue*.png output/acme_registrations*.png
