#!/bin/bash
cat << EOT
# plot_time_series

The plot_time_series is a simple utility for plotting a time_series graph using R
with some flexibility. This is handy for e.g. plotting KPI values over time.

## Installation

To use this script, you need to [install R](http://cran.r-project.org/mirrors.html) and then get the \`getopt\` package. 
To install the \`getopt\` package, fire up R (type R in your terminal) and type in something like:

    install.packages('getopt', repos='http://cran.us.r-project.org')

If your R binary is somewhere other than \`/usr/bin\` you'll need to edit the first line of \`plot_time_series\` to point it at the correct location. Do \`which R\` to find it.

## Usage

EOT

../plot_time_series -h 2>/dev/null | sed "s/^/    /"

cat << EOT

## Testing

There is a test directory with some lovely testy stuff in it:

    test/test_data - a directory with some test csv files in it
    test/output    - a directory that the test script dumps images into
    run_test       - a bash script that calls plot_time_series to generate a few graphs

    $ cd test
    $ ./run_test 
    $ ls output/*.png

## Examples

Example graphs are shown below. These are produced by from the data in the \`test\` directory

#### A simple graph showing registrations by time
![registrations by time](https://raw.github.com/doofdoofsf/plotTimeSeries/master/test/output/acme_registrations_thumb.png)

    plot_time_series --verbose --width=500 --height=400 --x_spacing=month --csv_filename=test_data/acme_registrations.csv --output_filename=output/acme_registrations_thumb.png --point_color=gray80 --sunday_point_color=gray80 --remove_outliers --smoothness=0.8

#### The same graph with a bit more detail
![registrations by time](https://raw.github.com/doofdoofsf/plotTimeSeries/master/test/output/acme_registrations.png)

    plot_time_series --verbose --width=1200 --height=700 --x_spacing=week --csv_filename=test_data/acme_registrations.csv --output_filename=output/acme_registrations.png --show_gridlines --title="Acme Registrations: %s to %s" --y_title="Number Registrations" --remove_outliers

#### A graph showing revenue with targets called out
![registrations by time](https://raw.github.com/doofdoofsf/plotTimeSeries/master/test/output/acme_revenue_targets.png)

    plot_time_series --verbose --width=1200 --height=700 --x_spacing=week --csv_filename=test_data/acme_revenue.csv --output_filename=output/acme_revenue_targets.png --show_gridlines --title="Acme Revenue: %s to %s" --remove_outliers --special_points_filename=test_data/acme_revenue_targets.csv --special_points_color=blue
EOT
