#!/bin/bash
cat << EOT
# plot_time_series

The plot_time_series is a simple utility for plotting a time_series graph using R
with some flexibility. This is handy for e.g. plotting KPI values over time.

## Installation

To use this script, you need to [install R](http://cran.r-project.org/mirrors.html) and then get the \`getopt\` package. 
To install the \`getopt\` package, fire up R (type R in your terminal) and type in something like:

    install.packages('getopt', repos='http://cran.us.r-project.org')

If your R binary is somewhere other than \`/usr/bin\` you'll need to edit the first line of \`plot_time_series\` to point it at the correct location. Do \`which R\` to find it.

## Usage

EOT

../plot_time_series -h 2>/dev/null | sed "s/^/    /"

cat << EOT

## Testing

There is a test directory with some lovely testy stuff in it:

    test/test_data - a directory with some test csv files in it
    test/output    - a directory that the test script dumps images into
    run_test       - a bash script that runs the tests
    tests.txt      - the test definitions

Go and run the tests and make sure everything passes:

    $ cd test
    $ ./run_test 
EOT

(cd ../test ; ./run_test) | sed "s/^/    /"

./generate_test_documentation
